dist: xenial
sudo: false

language: python
cache: pip

python:
  - "3.6"
  - "3.7"

install:
  - python setup.py develop
  - pip install coveralls -r requirements.txt

script:
  - flake8
  - black --check ./
  - coverage run --source full_yaml_metadata -m pytest

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PyPiLogin
  password: $PyPiPassword
  on:
    tags: true
    python: 3.7
